on: push
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust toolchain with caching
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Check formatting
        run: cargo fmt --all -- --check
        shell: bash
      - name: Check source
        run: cargo check
        shell: bash
      - name: Run tests
        run: cargo test
        shell: bash
